### ISSUE TITLE
Galaxy Nexus Android 4.3 Gets too much decimal places from file

### ISSUE THREAD

**Issue by codemonkeybr** [M1cha/android_app_cputempinstatusbar#1]
On my Galaxy Nexus running Stock Android 4.3 or ParanoidAndroid 
shows temperatures like 58000.0 .... 
it gets the data from "/sys/devices/platform/omap/omap_temp_sensor.0/temperature"
so as carry freqMode == 0

--the fix--
i downloaded the code, fixed, and i would like to commit my change, just a little if 
freq > 1000
then divide 1000f

**Comment by M1cha** [comment]
in latest version u can configure this
