### ISSUE TITLE
Does not work on Nexus 7 2013/FHD running CM nightlies

### ISSUE THREAD

**Issue by Efreak** [M1cha/android_app_cputempinstatusbar#4]
I also have to hit 'search temp files' to get the log--I don't know if this is normal/intended behavior, though I do know the button is there for a reason. In any case, the /sys hwmon files that it seems to be searching for are easily located, so the issue does not lie with the file location.

Device: Nexus 7 2013/FHD
Android Version: 4.4
Cyanogenmod Version: 11.0 Nightly (nearly every nightly release since cputemp release)
Codename: flo

Loaded Xposed Modules that affect the status bar:
[Notification Mod](http://repo.xposed.info/module/com.labtech.mod) 
[Tinted Status Bar](http://repo.xposed.info/module/com.mohammadag.colouredstatusbar) 1.6.1
[XBlast Tools](http://repo.xposed.info/module/ind.fem.black.xposed.mods) 1.7.0
[XuiMod](http://repo.xposed.info/module/com.zst.xposed.xuimod) 2.0.1 (module is active, statusbar settings are not)

I can't copy/paste the debug log, because you haven't made the text selectable. So I took a screenshot of it instead. If you need me to screenshot more of the log, or you want the logfile itself (and can tell me where it is), let me know.
![screenshot_2013-12-27-14-41-01](https://f.cloud.github.com/assets/749751/1816687/5e3b5adc-6f49-11e3-904f-61c111678617.png)

**Comment by M1cha** [comment]
does it work in latest version now?
